version: '3'
services:
  db:
    image: "postgres:14"
    ports:
      - 5432:5432
    tmpfs:
      - /var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_DB: loungy
